apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
spec:
  ingressClassName: {{ .Values.jellyfin.ingressClassName }}
  rules:
    - host: {{ .Values.jellyfin.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-service
                port:
                  name: http-tcp
