apiVersion: v1
kind: Secret
metadata:
  name: transmission-secrets
  namespace: house-infra
  labels:
    app: transmission
type: Opaque
data:
  transmission-password: {{ .Values.transmission.password | b64enc }}
