# kind: Service
# apiVersion: v1
# metadata:
#     name: transmission-service
# spec:
#     type: ClusterIP
#     selector:
#         app: transmission
#     ports:
#     - protocol: TCP
#       name: web-interface
#       port: 9091
#     - protocol: TCP
#       name: torrent-tcp
#       port: 51413
#     - protocol: UDP
#       name: torrents-udp
#       port: 51413
