apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zilinjak/homelab-k8s.git'
    targetRevision: HEAD
    path: helm/cert-manager
    helm:
      values: |
        crds:
          enable: true
          keep: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
