apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://pajikos.github.io/home-assistant-helm-chart/
    chart: home-assistant
    targetRevision: 0.3.22
    helm:
      values: |
        hostNetwork: true
        dnsPolicy: ClusterFirstWithHostNet
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: home-assistant.internal.zilinek.fun
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          enabled: true
          storageClass: longhorn
          size: 5Gi
        configuration:
          enabled: true
          trusted_proxies:
            - 10.42.0.0/16
            - 10.43.0.0/16
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
