apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zilinjak/homelab-k8s.git'
    targetRevision: HEAD
    path: helm/longhorn
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          host: longhorn.internal.zilinek.fun
        metrics:
          serviceMonitor:
            enabled: true
            
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
