apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zilinjak/homelab-k8s.git'
    targetRevision: HEAD
    path: helm/metallb
    helm:
      values: |
        # prometheus:
        #   serviceMonitor:
        #     enabled: true
        controller:
          logLevel: debug

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metal-lb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true