apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/zilinjak/homelab-k8s.git"
    targetRevision: HEAD
    path: helm/opentelemetry-collector
    helm:
      values: |
        mode: deployment

        replicaCount: 1

        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.142.0

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi

        service:
          type: ClusterIP

        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318

          processors:
            batch:
              timeout: 10s
              send_batch_size: 1024
            memory_limiter:
              check_interval: 1s
              limit_mib: 50
          
          exporters:
            # Tempo for traces
            otlp/tempo:
              endpoint: tempo.monitoring.svc.cluster.local:4317
              tls:
                insecure: true
            
            # Loki for logs (using OTLP)
            otlphttp/loki:
              endpoint: http://loki-gateway.monitoring.svc.cluster.local/otlp
              tls:
                insecure: true
            
            # Prometheus for metrics
            prometheusremotewrite:
              endpoint: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
              tls:
                insecure: true
            
            # Debug exporter
            debug:
              verbosity: normal
          
          service:
            pipelines:
              traces:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlp/tempo, debug]
              metrics:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [prometheusremotewrite, debug]
              logs:
                receivers: [otlp]
                processors: [memory_limiter, batch]
                exporters: [otlphttp/loki, debug]
        podMonitor:
          enabled: true
        serviceMonitor:
          enabled: true
        ports:
          metrics:
            enabled: true
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: otel-collector.internal.zilinek.fun
              paths:
                - path: /
                  pathType: Prefix
                  port: 4318

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
