apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://mojo2600.github.io/pihole-kubernetes/
    chart: pihole
    targetRevision: 2.27.0
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
          - pihole.internal.zilinek.fun
        serviceWeb:
          type: ClusterIP
        adminPassword: "admin"
        serviceDns:
          type: LoadBalancer
        podDnsConfig:
          nameservers:
            - 8.8.8.8
        serviceDns:
          mixedService: true
          type: LoadBalancer
          loadBalancerIP: 192.168.0.242
        

  destination:
    server: https://kubernetes.default.svc
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
