apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zilinjak/homelab-k8s.git'
    targetRevision: HEAD
    path: helm/plex-media-server
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: "nginx"
          url: "plex.internal.zilinek.fun"
        pms:
          storageClassName: "longhorn-static"
          configStorage: 50Gi
        extraEnv:
          # The claim is obtained from https://www.plex.tv/claim/ is is only valid for a few minutes
          PLEX_CLAIM: "claim-yLMSPYGCRyfjes6EuMxK"
  destination:
    server: https://kubernetes.default.svc
    namespace: plex-media-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
