apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-media-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zilinjak/homelab-k8s.git'
    targetRevision: HEAD
    path: helm/plex-media-server
    helm:
      values: |
        transmission:
          host: transmission.internal.zilinek.fun
        ingress:
          enabled: true
          ingressClassName: "nginx"
          url: "plex.internal.zilinek.fun"
        publicIngress:
          enabled: true
          ingressClassName: "nginx-external"
          url: "plex.zilinek.fun"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
        pms:
          storageClassName: "longhorn-static"
          configStorage: 500Gi
        extraEnv:
          # The claim is obtained from https://www.plex.tv/claim/ is is only valid for a few minutes
          PLEX_CLAIM: "claim-i5z_UziXs5edx_6eg-o6"
  destination:
    server: https://kubernetes.default.svc
    namespace: plex-media-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
