apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
spec:
  addresses:
    - 192.168.0.240-192.168.0.242
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
spec:
  ipAddressPools:
    - metallb-pool
